#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor eDP-1 -d 1 2 3 4 5 6
bspc monitor HDMI1 -d 7 8 9

bspc config border_width 5
bspc config window_gap 6

bspc config split_ratio 0.52
bspc config borderless_monocle false
bspc config gapless_monocle false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# COLOR SCHEME
bspc config normal_border_color "#484848"
bspc config focused_border_color "#1F8999"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

# AUTO START PROGRAMS
picom --config $HOME/.config/picom/picom.conf &
feh --bg-scale ~/Pictures/wallpaper.jpg &
exec ~/.config/polybar/launch.sh &
dunst
